theme: osuny-hugo-theme-aaa
paginate: 18
enableRobotsTXT: true
removePathAccents: true
params:
  search:
    active: true
  breadcrumb:
    position: after-hero
  logo:
    header: "/assets/images/logo.svg"
    footer: "/assets/images/logo-blanc.svg"
  summary:
    position: "content"
  image_sizes:
    design_system:
      lightbox:
        disabled: true
      hero:
        mobile:   400
        tablet:   800
        desktop:  1300