theme: osuny-hugo-theme-aaa
paginate: 18
enableRobotsTXT: true
removePathAccents: true
params:
  search:
    active: true
  breadcrumb:
    position: after-hero
  logo:
    header: "/assets/images/logo.svg"
    footer: "/assets/images/logo-blanc.svg"
  summary:
    position: "hero"
  image_sizes:
    design_system:
      lightbox:
        disabled: true
      hero:
        mobile:   400
        tablet:   800
        desktop:  2000
    sections:
      home:
        hero:
          mobile:   400
          tablet:   800
          desktop:  2000
      programs:
        hero:
          mobile:   400
          tablet:   800
          desktop:  2000
        item:
          mobile:   350
          tablet:   450
          desktop:  600
      posts:
        hero_single:
          mobile:   400
          tablet:   800
          desktop:  2000