theme: osuny-hugo-theme-aaa
paginate: 18
enableRobotsTXT: true
removePathAccents: true
params:
  search:
    active: false
  logo:
    header: "/assets/images/logo.png"
    footer: "/assets/images/logo.png"