baseURL: https://www-bw.iut.u-bordeaux.fr

## LANGUAGE
defaultContentLanguage: fr
defaultContentLanguageInSubdir: false

## CACHE
deployment:
  matchers:
    - pattern: "^.+\\.(woff2|woff|svg|ttf|eot|js|css)$"
      cacheControl: "max-age=31536000, no-transform, public"
      gzip: true
    - pattern: "^.+\\.(png|jpg|jpeg|gif|webp)$"
      cacheControl: "max-age=31536000, no-transform, public"
      gzip: false
